# Generated by Django 2.0.5 on 2018-05-02 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=50)),
                ('thumbnail', models.CharField(max_length=100)),
                ('fact', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Artwork',
            },
        ),
        migrations.CreateModel(
            name='ArtworkAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=300)),
                ('weight', models.IntegerField()),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curator.Artwork')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('activity', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Galleries',
            },
        ),
        migrations.AddField(
            model_name='artwork',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curator.Gallery'),
        ),
    ]
