# Generated by Django 2.0.5 on 2018-05-03 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=800)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curator.Gallery')),
            ],
            options={
                'verbose_name_plural': 'Gallery activities',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curator.Artwork')),
            ],
        ),
        migrations.CreateModel(
            name='ReactionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curator.Persona')),
            ],
        ),
        migrations.AddField(
            model_name='reaction',
            name='reaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curator.ReactionType'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curator.Visitor'),
        ),
        migrations.AddField(
            model_name='galleryactivity',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curator.Persona'),
        ),
        migrations.AlterUniqueTogether(
            name='galleryactivity',
            unique_together={('gallery', 'persona')},
        ),
    ]
