# Generated by Django 2.0.5 on 2018-05-03 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0002_auto_20180503_0325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='activity',
        ),
    ]
