# Generated by Django 2.0.5 on 2018-05-09 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0003_remove_gallery_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryactivity',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
